/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Variable = IDL.Record({
  'coefficient' : IDL.Float64,
  'name' : IDL.Text,
});
export const Constraint = IDL.Record({
  'value' : IDL.Float64,
  'operator' : IDL.Text,
  'variables' : IDL.Vec(Variable),
});
export const FeedbackEntry = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'problemContext' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserActivity = IDL.Record({
  'firstSeen' : IDL.Int,
  'principal' : IDL.Principal,
  'visitCount' : IDL.Nat,
  'solveCount' : IDL.Nat,
  'lastLogin' : IDL.Int,
  'dualSimplexCount' : IDL.Nat,
  'location' : IDL.Text,
  'simplexCount' : IDL.Nat,
  'cuttingPlaneCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const FeedbackStats = IDL.Record({
  'totalCount' : IDL.Nat,
  'averageRating' : IDL.Float64,
});
export const LPProblem = IDL.Record({
  'id' : IDL.Nat,
  'constraints' : IDL.Vec(Constraint),
  'owner' : IDL.Principal,
  'objective' : IDL.Vec(Variable),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isMaximize' : IDL.Bool,
});
export const LPPSolution = IDL.Record({
  'status' : IDL.Text,
  'problemId' : IDL.Nat,
  'variables' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'objectiveValue' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProblem' : IDL.Func(
      [IDL.Text, IDL.Vec(Variable), IDL.Bool, IDL.Vec(Constraint)],
      [IDL.Nat],
      [],
    ),
  'deleteProblem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getAllUserActivity' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeedbackStats' : IDL.Func([], [FeedbackStats], ['query']),
  'getProblem' : IDL.Func([IDL.Nat], [IDL.Opt(LPProblem)], ['query']),
  'getSolution' : IDL.Func([IDL.Nat], [IDL.Opt(LPPSolution)], ['query']),
  'getUserActivity' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserActivity)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProblems' : IDL.Func([], [IDL.Vec(LPProblem)], ['query']),
  'listMyProblems' : IDL.Func([], [IDL.Vec(LPProblem)], ['query']),
  'recordLogin' : IDL.Func([IDL.Text], [], []),
  'recordSolve' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'solveProblem' : IDL.Func([IDL.Nat], [IDL.Opt(LPPSolution)], []),
  'submitFeedback' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Variable = IDL.Record({
    'coefficient' : IDL.Float64,
    'name' : IDL.Text,
  });
  const Constraint = IDL.Record({
    'value' : IDL.Float64,
    'operator' : IDL.Text,
    'variables' : IDL.Vec(Variable),
  });
  const FeedbackEntry = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'problemContext' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserActivity = IDL.Record({
    'firstSeen' : IDL.Int,
    'principal' : IDL.Principal,
    'visitCount' : IDL.Nat,
    'solveCount' : IDL.Nat,
    'lastLogin' : IDL.Int,
    'dualSimplexCount' : IDL.Nat,
    'location' : IDL.Text,
    'simplexCount' : IDL.Nat,
    'cuttingPlaneCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const FeedbackStats = IDL.Record({
    'totalCount' : IDL.Nat,
    'averageRating' : IDL.Float64,
  });
  const LPProblem = IDL.Record({
    'id' : IDL.Nat,
    'constraints' : IDL.Vec(Constraint),
    'owner' : IDL.Principal,
    'objective' : IDL.Vec(Variable),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isMaximize' : IDL.Bool,
  });
  const LPPSolution = IDL.Record({
    'status' : IDL.Text,
    'problemId' : IDL.Nat,
    'variables' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'objectiveValue' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProblem' : IDL.Func(
        [IDL.Text, IDL.Vec(Variable), IDL.Bool, IDL.Vec(Constraint)],
        [IDL.Nat],
        [],
      ),
    'deleteProblem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getAllUserActivity' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeedbackStats' : IDL.Func([], [FeedbackStats], ['query']),
    'getProblem' : IDL.Func([IDL.Nat], [IDL.Opt(LPProblem)], ['query']),
    'getSolution' : IDL.Func([IDL.Nat], [IDL.Opt(LPPSolution)], ['query']),
    'getUserActivity' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserActivity)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProblems' : IDL.Func([], [IDL.Vec(LPProblem)], ['query']),
    'listMyProblems' : IDL.Func([], [IDL.Vec(LPProblem)], ['query']),
    'recordLogin' : IDL.Func([IDL.Text], [], []),
    'recordSolve' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'solveProblem' : IDL.Func([IDL.Nat], [IDL.Opt(LPPSolution)], []),
    'submitFeedback' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };