/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Constraint {
  'value' : number,
  'operator' : string,
  'variables' : Array<Variable>,
}
export interface FeedbackEntry {
  'id' : bigint,
  'principal' : Principal,
  'name' : [] | [string],
  'email' : [] | [string],
  'comment' : string,
  'timestamp' : bigint,
  'problemContext' : string,
  'rating' : bigint,
}
export interface FeedbackStats {
  'totalCount' : bigint,
  'averageRating' : number,
}
export interface LPPSolution {
  'status' : string,
  'problemId' : bigint,
  'variables' : Array<[string, number]>,
  'objectiveValue' : [] | [number],
}
export interface LPProblem {
  'id' : bigint,
  'constraints' : Array<Constraint>,
  'owner' : Principal,
  'objective' : Array<Variable>,
  'name' : string,
  'createdAt' : bigint,
  'isMaximize' : boolean,
}
export interface UserActivity {
  'firstSeen' : bigint,
  'principal' : Principal,
  'visitCount' : bigint,
  'solveCount' : bigint,
  'lastLogin' : bigint,
  'dualSimplexCount' : bigint,
  'location' : string,
  'simplexCount' : bigint,
  'cuttingPlaneCount' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Variable { 'coefficient' : number, 'name' : string }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProblem' : ActorMethod<
    [string, Array<Variable>, boolean, Array<Constraint>],
    bigint
  >,
  'deleteProblem' : ActorMethod<[bigint], boolean>,
  'getAllFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'getAllUserActivity' : ActorMethod<[], Array<UserActivity>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeedbackStats' : ActorMethod<[], FeedbackStats>,
  'getProblem' : ActorMethod<[bigint], [] | [LPProblem]>,
  'getSolution' : ActorMethod<[bigint], [] | [LPPSolution]>,
  'getUserActivity' : ActorMethod<[Principal], [] | [UserActivity]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllProblems' : ActorMethod<[], Array<LPProblem>>,
  'listMyProblems' : ActorMethod<[], Array<LPProblem>>,
  'recordLogin' : ActorMethod<[string], undefined>,
  'recordSolve' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'solveProblem' : ActorMethod<[bigint], [] | [LPPSolution]>,
  'submitFeedback' : ActorMethod<
    [[] | [string], [] | [string], bigint, string, string],
    bigint
  >,
  'claimAdminWithToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
